import {
  Decimal,
  MONEY_SCALE,
  PCT_SCALE,
  addMonthsIso,
  toFixedString,
  type ProgressEntry,
} from '@unita/engine';
import type {
  FeeRecalibrationBody,
  FeeRecalibrationResponse,
  ProgressIndicatorsBody,
  ProgressIndicatorsDto,
} from '@unita/contracts';
import type { Db } from '../../database/client.js';
import { auditRepository } from '../../database/repositories/audit.repository.js';
import {
  feeRecalibrationsRepository,
  progressIndicatorsRepository,
  type ProgressIndicatorRow,
} from '../../database/repositories/consolidated-inputs.repository.js';
import { projectionsRepository } from '../../database/repositories/projections.repository.js';
import { worksRepository, type WorkRow } from '../../database/repositories/works.repository.js';
import type { Actor, AppDeps, AuthUser } from '../../types.js';
import { notFound } from '../../utils/errors.js';
import { generateProjection, manualFromValues } from '../projections/projections.service.js';

const fraction = (v: string | null | undefined) =>
  v === null || v === undefined ? null : toFixedString(new Decimal(v), PCT_SCALE);

function toIndicatorsDto(workId: string, rows: ProgressIndicatorRow[]): ProgressIndicatorsDto {
  const last = rows.reduce<ProgressIndicatorRow | null>(
    (acc, r) => (!acc || r.updatedAt > acc.updatedAt ? r : acc),
    null,
  );
  return {
    workId,
    source: last?.source ?? null,
    updatedAt: last?.updatedAt.toISOString() ?? null,
    months: rows.map((r) => ({
      month: r.month,
      realizedCumulative: r.realizedCumulative,
      clientReplannedCumulative: r.clientReplannedCumulative,
      targetCumulative: r.targetCumulative,
    })),
  };
}

/** Canonical entries (8 decimals, months without any value dropped). */
export function canonicalProgressEntries(
  months: ProgressIndicatorsBody['months'],
): ProgressEntry[] {
  return months
    .map((m) => ({
      month: m.month.length === 7 ? `${m.month}-01` : m.month,
      realizedCumulative: fraction(m.realizedCumulative),
      clientReplannedCumulative: fraction(m.clientReplannedCumulative),
      targetCumulative: fraction(m.targetCumulative),
    }))
    .filter(
      (m) =>
        m.realizedCumulative !== null ||
        m.clientReplannedCumulative !== null ||
        m.targetCumulative !== null,
    )
    .sort((a, b) => (a.month < b.month ? -1 : 1));
}

/** Stores the progress indicators of a work (used by the API endpoint and the SharePoint sync). */
export async function saveProgressIndicators(
  tx: Db,
  workId: string,
  body: { source: string; externalRef?: string | null; entries: ProgressEntry[] },
  actor: Actor,
): Promise<void> {
  await progressIndicatorsRepository.replace(
    tx,
    workId,
    {
      source: body.source,
      externalRef: body.externalRef ?? null,
      receivedVia: actor.integration ? 'API_KEY' : 'USER',
      updatedById: actor.user?.id ?? null,
    },
    body.entries,
  );
  const last = body.entries.at(-1);
  await auditRepository.insert(tx, {
    userId: actor.user?.id ?? null,
    action: 'IMPORT_PROGRESS',
    entity: 'work_progress_indicators',
    entityId: null,
    workId,
    newValue: `${body.entries.length} meses${last ? ` · último ${last.month.slice(0, 7)}` : ''}`,
    origin: body.source,
    metadata: { integration: actor.integration, externalRef: body.externalRef ?? null },
  });
}

/**
 * Inputs typed or received for the "Consolidado": planning-system progress indicators and
 * the fee recalibration ("Ajuste projeção de taxa"). Every change is audited and — for the
 * recalibration — produces a new projection version generated by the engine.
 */
export function createConsolidatedInputsService({ db }: AppDeps) {
  async function loadWork(tx: Db, workId: string): Promise<WorkRow> {
    const found = await worksRepository.findById(tx, workId);
    if (!found) throw notFound('Obra');
    return found.work;
  }

  async function currentFee(tx: Db, workId: string) {
    const current = await projectionsRepository.findCurrent(tx, workId);
    if (!current) throw notFound('Projeção');
    const values = await projectionsRepository.getValues(tx, current.projection.id);
    return { projection: current.projection, values };
  }

  const sumFrom = (
    values: { series: string; periodMonth: string; currentValue: string }[],
    from: string,
  ) =>
    toFixedString(
      values
        .filter((v) => v.series === 'FEE' && v.periodMonth >= from)
        .reduce((acc, v) => acc.plus(v.currentValue), new Decimal(0)),
      MONEY_SCALE,
    );

  return {
    async getProgress(workId: string): Promise<ProgressIndicatorsDto> {
      await loadWork(db, workId);
      return toIndicatorsDto(workId, await progressIndicatorsRepository.listByWork(db, workId));
    },

    async putProgress(
      workId: string,
      body: ProgressIndicatorsBody,
      actor: Actor,
    ): Promise<ProgressIndicatorsDto> {
      await loadWork(db, workId);
      const entries = canonicalProgressEntries(body.months);
      await db.transaction((tx) => saveProgressIndicators(tx, workId, { ...body, entries }, actor));
      return toIndicatorsDto(workId, await progressIndicatorsRepository.listByWork(db, workId));
    },

    /**
     * Stores the new Σ fee to be received after `referenceMonth` and regenerates the projection
     * (manual cells preserved). An engine rejection rolls everything back (422).
     */
    async setRecalibration(
      workId: string,
      body: FeeRecalibrationBody,
      user: AuthUser,
    ): Promise<FeeRecalibrationResponse> {
      const work = await loadWork(db, workId);
      const referenceMonth =
        body.referenceMonth.length === 7 ? `${body.referenceMonth}-01` : body.referenceMonth;
      const fromMonth = addMonthsIso(referenceMonth, 1);
      return db.transaction(async (tx) => {
        const { values } = await currentFee(tx, workId);
        const previousRemaining = sumFrom(values, fromMonth);
        const remainingTotal = toFixedString(new Decimal(body.remainingTotal), MONEY_SCALE);
        const row = await feeRecalibrationsRepository.create(tx, {
          workId,
          referenceMonth,
          fromMonth,
          remainingTotal,
          previousRemaining,
          note: body.note ?? null,
          createdById: user.id,
        });
        const { row: projection } = await generateProjection(tx, work, user, {
          mode: 'PRESERVE_MANUAL',
          manualCells: manualFromValues(values),
          note: `Ajuste projeção de taxa a partir de ${fromMonth.slice(0, 7)}`,
        });
        await auditRepository.insert(tx, {
          userId: user.id,
          action: 'FEE_RECALIBRATION',
          entity: 'fee_recalibration',
          entityId: row.id,
          workId,
          field: `Taxa a receber a partir de ${fromMonth.slice(0, 7)}`,
          oldValue: previousRemaining,
          newValue: remainingTotal,
          origin: 'MANUAL',
          metadata: { version: projection.version, referenceMonth, note: body.note ?? null },
        });
        return {
          recalibration: {
            id: row.id,
            referenceMonth: row.referenceMonth,
            fromMonth: row.fromMonth,
            remainingTotal: row.remainingTotal,
            previousRemaining: row.previousRemaining,
            note: row.note,
            createdBy: user.name,
            createdAt: row.createdAt.toISOString(),
            applied: true,
          },
          projectionVersion: projection.version,
        };
      });
    },

    /** Removes the recalibration: the fee returns to orçamento × taxa spread by the curve. */
    async clearRecalibration(workId: string, user: AuthUser): Promise<FeeRecalibrationResponse> {
      const work = await loadWork(db, workId);
      return db.transaction(async (tx) => {
        const cleared = await feeRecalibrationsRepository.clearCurrent(tx, workId);
        if (!cleared) throw notFound('Ajuste de taxa');
        const { values } = await currentFee(tx, workId);
        const { row: projection } = await generateProjection(tx, work, user, {
          mode: 'PRESERVE_MANUAL',
          manualCells: manualFromValues(values),
          note: 'Ajuste projeção de taxa removido',
        });
        await auditRepository.insert(tx, {
          userId: user.id,
          action: 'FEE_RECALIBRATION_CLEARED',
          entity: 'fee_recalibration',
          entityId: cleared.id,
          workId,
          field: `Taxa a receber a partir de ${cleared.fromMonth.slice(0, 7)}`,
          oldValue: cleared.remainingTotal,
          newValue: null,
          origin: 'CURVE',
          metadata: { version: projection.version },
        });
        return { recalibration: null, projectionVersion: projection.version };
      });
    },
  };
}
